# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # workflow_dispatch:

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm test
# npm run build --if-present
        

#   web-deploy:
#     name: Deploy Backend
#     runs-on: ubuntu-latest
        
#     steps:
#     - name: Build Project
#       run: |
#         npm run build
    
#     - name: List output files
#       run: find build/ -print
      
#     - name: Deploy to Server
#       uses: 
#       with:
#         username: ''
#         server: ''
#         ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
