# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
  
    - name: create env file
      run: |
        touch .env
        echo GENERATE_SOURCEMAP=false >> .env
        echo REACT_APP_BACKEND_API=${{ secrets.REACT_APP_BACKEND_API }} >> .env
        
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
      
#     - name: Deploy to Server
#       uses: wlixcc/SFTP-Deploy-Action@v1.0
#       with:
#         username: 'root'
#         server: '3.109.88.68'
#         ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
#         local_path: 'build/*'
#         remote_path: '/var/www/html/charrycoin.com'
#         args: '-o ConnectTimeout=5'
